# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

  commands:
    - pip install --upgrade --no-cache-dir pip
    - pip install --no-cache-dir "poetry>=1.4" "crashtest==0.4.1"
    - poetry install --with=doc --without=test
    - poetry run make html -C docs
    - cp -r docs/build _readthedocs
