name: test
on: [push, pull_request, release]
jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          version: "0.5.15"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: all
        run: make all
      - name: Upload coverage data to coveralls.io
        run: |
          pip3 install --upgrade coveralls
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.test-name }}
          COVERALLS_PARALLEL: true
  coveralls:
    name: Indicate completion to coveralls.io
    needs: build
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finished
        run: |
          pip3 install --upgrade coveralls
          coveralls --service=github --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    if: github.event_name == 'push' && github.ref_type == 'tag'
    name: Upload release to PyPI
    needs: coveralls
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          version: "0.5.15"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: build
        run: uv build
      - name: publish
        run: uv publish
